### ISSUE TITLE
Exception when validating javascript code calling argumentless require() function

### ISSUE THREAD

**Issue by Georgeto** [mozilla/amo-validator#572]
When validating the extension contained in [this archive](https://github.com/mozilla/amo-validator/files/1380628/sieve.zip) I get the following stacktrace and error description.

```ERROR:amo.validator:Unexpected error during validation: IndexError: list index out of range
Traceback (most recent call last):
  File ".../amo-validator/validator/testcases/javascript/traverser.py", line 82, in run
    func()
  File ".../amo-validator/validator/testcases/javascript/actions.py", line 187, in wrap
    traverser._traverse_node(node['body'])
  File ".../amo-validator/validator/testcases/javascript/traverser.py", line 192, in _traverse_node
    map(self._traverse_node, b)
  File ".../amo-validator/validator/testcases/javascript/traverser.py", line 168, in _traverse_node
    action_result = action(self, node)
  File ".../amo-validator/validator/testcases/javascript/actions.py", line 602, in _expression
    return traverser._traverse_node(node['expression'])
  File ".../amo-validator/validator/testcases/javascript/traverser.py", line 168, in _traverse_node
    action_result = action(self, node)
  File ".../amo-validator/validator/testcases/javascript/actions.py", line 444, in _call_expression
    e=traverser.err)
  File ".../amo-validator/validator/testcases/javascript/actions.py", line 527, in _call_require
    module = traverse(args[0]).get_literal_value()
IndexError: list index out of range


Summary:
------------------------------
Detected type: Extension/Multi-Extension
------------------------------
Test failed! Errors:

Error:	An unexpected error has occurred.
Validation was unable to complete successfully due to an unexpected error.
The error has been logged, but please consider filing an issue report here: https://bit.ly/1POrYYU
	Tier:	1
	File:	common/libSieve/SieveSimpleGui.html
	Line:	172
	Column:	12
	Context:
	>    <button onclick="require()">
	>   Collect Require
	> </button>
...
```

After a little bit of debugging I found the following function being responsible.
https://github.com/mozilla/amo-validator/blob/a5c0d245f81aa37a25450e0c6757bb5bf28aa688/validator/testcases/javascript/actions.py#L517-L527
The exception happens in line 527, where `args[0]` is accessed without checking the argument count of the call to `require()`, which also could be a user defined function. The if statement in line 524 looks suspicious to me.

**Comment by EnTeQuAk** [comment]
Closing as we're deprecating this tool and legacy add-ons are only allowed for updates, not new submissions.
